import AppKit

/// 轮询系统剪贴板，发现新的纯文本时回调。
final class ClipboardMonitor {
    /// 密码管理器等应用用这些类型标记不应被记录的内容（见 nspasteboard.org）。
    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private let onNewText: (String) -> Void

    init(onNewText: @escaping (String) -> Void) {
        self.onNewText = onNewText
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    private func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: Self.ignoredTypes),
              let text = pasteboard.string(forType: .string)
        else { return }
        onNewText(text)
    }
}
